### ISSUE TITLE
Link Validation, bug 

### ISSUE THREAD

**Issue by lflachs** [chudaol/workademy#48]
You should validate if it's a link, in this case, if the user is just typing http, it will work, but it shouldn't because it's not a link
Check here there is a regex for that:
https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url

_Originally posted by @lflachs in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDAwNDI0NTc1/pull_request_reviews/more_threads_

**Comment by lflachs** [comment]
https://www.loom.com/share/c853f402dd514e2eaa1258804fd0f025

**Comment by miaypc** [comment]
fix

**Comment by miaypc** [comment]
fixed #48

**Comment by miaypc** [comment]
Closes #48
